[package]
name = "siwe_ex"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ethers-core = "2.0.14"
hex = "0.4.3"
http = "1.3.1"
iri-string = "0.7.8"
rustler = "0.37.0"
siwe = "0.6.1"
time = "0.3.44"
tokio = { version = "1.48.0", features = ["full"] }
